<?= view('includes/header', ['title' => 'Terms and Conditions']) ?>

    <main>
      
        <div class="hero medium-height jarallax" data-jarallax data-speed="0.2">
            <img class="jarallax-img" src="images/bar01.jpg" alt="">
            <div class="wrapper opacity-mask d-flex align-items-center justify-content-center text-center animate_hero" data-opacity-mask="rgba(0, 0, 0, 0.5)">
                <div class="container">
                    <div class="hedintextp">
                        <h3 class="slide-animated two">Terms and Conditions</h3>
                    </div>
                </div>
            </div>
        </div>

   
        <div class="container pt-5 pb-4">
           <div class="row mt-3">
                <div class="col-md-12">
                    <h6>1. Acceptance of Terms</h6>

                    <p>By accessing and using the Missing Person Finder website ("the Website"), you agree to comply with and be bound by the following terms and conditions. If you do not agree with these terms, please do not use the Website.</p>

                    <h6>2. Use of Face Recognition Technology</h6>

                    <p>The Website utilizes face recognition technology to aid in the search for missing persons. By submitting a photograph for analysis, you acknowledge and consent to the use of this technology for the purpose of identifying and locating missing individuals.</p>

                    <h6>3. User Conduct</h6>

                    <p>a. You agree not to use the Website for any unlawful or prohibited purpose.</p>

                    <p>b. You shall not upload, distribute, or otherwise publish through the Website any content that is offensive, defamatory, or infringes on the rights of others.</p>

                    <h6>4. Privacy</h6>

                    <p>a. The Website takes user privacy seriously. Any personal information provided will be handled in accordance with our Privacy Policy.</p>

                    <p>b. Users are prohibited from using the face recognition technology for unauthorized purposes, including but not limited to stalking, harassment, or any illegal activities.</p>

                    <h6>5. Accuracy of Information</h6>

                    <p>a. While the Website strives to provide accurate and up-to-date information, it does not guarantee the accuracy of results generated by the face recognition technology.</p>

                    <p>b. Users are encouraged to verify the information obtained through the Website independently before taking any action.</p>

                    <h6>6. Limitation of Liability</h6>

                    <p>The Website, its owners, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of the use or inability to use the Website or the results generated by the face recognition technology.</p>

                    <h6>7. Changes to Terms</h6>

                    <p>The Website reserves the right to update or modify these terms and conditions at any time without prior notice. Users are responsible for regularly reviewing the terms.</p>

                    <h6>8. Governing Law</h6>

                    <p>These terms and conditions are governed by and construed in accordance with the laws of [your jurisdiction]. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the courts in [your jurisdiction].</p>

                    <h6>9. Contact Information</h6>

                    <p>If you have any questions or concerns about these terms and conditions, please contact to SourceCode.</p>


                </div>
            </div>
            <!-- /Row -->
        </div>
    </main>

    <?= view('includes/footer') ?>